/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/visualPanel.java to edit this template
 */
package com.data.acquisition.wizard;

import com.data.acquisition.DataAcquisitionAction;
import javax.swing.JPanel;

public final class DataAcquisitionVisualPanel3 extends JPanel {

    /**
     * Creates new form DataAcquisitionVisualPanel3
     */
    public DataAcquisitionVisualPanel3() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #3";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinationFileNameLbl = new javax.swing.JLabel();
        destinationFileNameTxt = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(destinationFileNameLbl, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel3.class, "DataAcquisitionVisualPanel3.destinationFileNameLbl.text")); // NOI18N

        destinationFileNameTxt.setText(org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel3.class, "DataAcquisitionVisualPanel3.destinationFileNameTxt.text")); // NOI18N
        destinationFileNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationFileNameTxtActionPerformed(evt);
            }
        });
        destinationFileNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                destinationFileNameTxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(destinationFileNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinationFileNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationFileNameLbl)
                    .addComponent(destinationFileNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void destinationFileNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationFileNameTxtActionPerformed
        DataAcquisitionVisualPanel4.setDestinationFileNamePath(this.destinationFileNameTxt.getText());
        DataAcquisitionAction.destinationFileName = this.destinationFileNameTxt.getText();
    }//GEN-LAST:event_destinationFileNameTxtActionPerformed

    private void destinationFileNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinationFileNameTxtKeyPressed
        DataAcquisitionVisualPanel4.setDestinationFileNamePath(this.destinationFileNameTxt.getText());
        DataAcquisitionAction.destinationFileName = this.destinationFileNameTxt.getText();
    }//GEN-LAST:event_destinationFileNameTxtKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinationFileNameLbl;
    private javax.swing.JTextField destinationFileNameTxt;
    // End of variables declaration//GEN-END:variables
}
