/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/visualPanel.java to edit this template
 */
package com.data.acquisition.wizard;

import javax.swing.JPanel;

public final class DataAcquisitionVisualPanel4 extends JPanel {

    /**
     * Creates new form DataAcquisitionVisualPanel4
     */
    public DataAcquisitionVisualPanel4() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #4";
    }
    
    public static void setSourcePath(String source) {
        DataAcquisitionVisualPanel4.sourceValueLbl.setText(source);
    }

    public static void setDestinationPath(String destination) {
        DataAcquisitionVisualPanel4.destinationValueLbl.setText(destination);
    }

    public static void setDestinationFileNamePath(String fileName) {
        DataAcquisitionVisualPanel4.destinationFileNameValueLbl.setText(fileName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sourceValueLbl = new javax.swing.JLabel();
        destinationValueLbl = new javax.swing.JLabel();
        destinationFileNameValueLbl = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sourceValueLbl, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.sourceValueLbl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(destinationValueLbl, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.destinationValueLbl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(destinationFileNameValueLbl, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel4.class, "DataAcquisitionVisualPanel4.destinationFileNameValueLbl.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourceValueLbl)
                    .addComponent(destinationValueLbl)
                    .addComponent(destinationFileNameValueLbl))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sourceValueLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(destinationValueLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(destinationFileNameValueLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel destinationFileNameValueLbl;
    public static javax.swing.JLabel destinationValueLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel sourceValueLbl;
    // End of variables declaration//GEN-END:variables
}
