/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/visualPanel.java to edit this template
 */
package com.data.acquisition.wizard;

import com.data.acquisition.DataAcquisitionAction;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public final class DataAcquisitionVisualPanel2 extends JPanel {

    JFileChooser chooser;
    String chooserTitle = "Pilih sumber";

    /**
     * Creates new form DataAcquisitionVisualPanel2
     */
    public DataAcquisitionVisualPanel2() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #2";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinationChooserLbl = new javax.swing.JLabel();
        destinationChooserBtn = new javax.swing.JButton();
        destinationChooserTxt = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(destinationChooserLbl, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel2.class, "DataAcquisitionVisualPanel2.destinationChooserLbl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(destinationChooserBtn, org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel2.class, "DataAcquisitionVisualPanel2.destinationChooserBtn.text")); // NOI18N
        destinationChooserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationChooserBtnActionPerformed(evt);
            }
        });

        destinationChooserTxt.setText(org.openide.util.NbBundle.getMessage(DataAcquisitionVisualPanel2.class, "DataAcquisitionVisualPanel2.destinationChooserTxt.text")); // NOI18N
        destinationChooserTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationChooserTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(destinationChooserLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinationChooserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinationChooserBtn)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationChooserLbl)
                    .addComponent(destinationChooserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationChooserBtn))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void destinationChooserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationChooserBtnActionPerformed
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(this.chooserTitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.destinationChooserTxt.setText(chooser.getSelectedFile().toString());

            DataAcquisitionVisualPanel4.setDestinationPath(this.destinationChooserTxt.getText());
            DataAcquisitionAction.destinationPath = this.destinationChooserTxt.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Konfirmasi", "Lokasi sumber belum dipilih.", JOptionPane.INFORMATION_MESSAGE);
        }

        // DataAcquisitionAction.jProgressBarFrame.setVisible(false);
    }//GEN-LAST:event_destinationChooserBtnActionPerformed

    private void destinationChooserTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationChooserTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationChooserTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton destinationChooserBtn;
    private javax.swing.JLabel destinationChooserLbl;
    private javax.swing.JTextField destinationChooserTxt;
    // End of variables declaration//GEN-END:variables
}
